Adiciona dados de relações entre as disciplinas
OpenDevUFCG/laguinho-api pull request #25
Opened 2019-04-13 21:10 UTC by fanny

2019-04-13 23:29 UTC, JuanBarros2 approved these changes
Por mim ta ótimo. Só precisa saber se continuaremos com esse modelo de disposição de dados ou adicionaremos eles no laguinho

2019-04-14 00:06 UTC, JoseRenan requested changes

2019-04-14 00:06 UTC, JoseRenan commented on src/v1/subjects/subj-data.js
>      return await csvtojson().fromString((await axios.get(csvFilePath)).data)
Os dois awaits nessa linha são necessários? acredito que só precisa do segundo pra dar certo :thinking:

2019-04-14 00:11 UTC, JuanBarros2 commented on src/v1/subjects/subj-data.js
>      return await csvtojson().fromString((await axios.get(csvFilePath)).data)
É porque o CSVTOJSON é uma chamada assincrona também. Pelo que vi na documentação deles...

2019-04-14 00:13 UTC, JuanBarros2 commented on src/v1/subjects/subj-data.js
>      return await csvtojson().fromString((await axios.get(csvFilePath)).data)
Quando eu não dava esse await aí ele retornava vazio. Acho que essa função cria uma promise

2019-04-14 00:14 UTC, JoseRenan approved these changes

2019-04-14 00:15 UTC, merged

2019-04-14 00:15 UTC, JoseRenan commented
> Só precisa saber se continuaremos com esse modelo de disposição de dados ou adicionaremos eles no laguinho

@JuanBarros2 a gente tá falando sobre isso lá no #23