Adiciona endpoint para publicar datasets
OpenDevUFCG/laguinho-api pull request #45
Opened 2019-09-06 19:47 UTC by lucasaarcoverde

Resolve #43  
Adiciona endpoint para publicar datasets e salva os JSON em memória

Forma de testar:
Fazer um post no endpoint `http://localhost:8080/datasets/publish` com um exemplo de [metadata](https://github.com/OpenDevUFCG/laguinho/issues/13) no body.

Para testar o que está sendo salvo basta fazer um get para o endpoint `http://localhost:8080/datasets/metadata`

2019-09-06 20:11 UTC, JoseRenan requested changes

2019-09-06 20:11 UTC, JoseRenan commented on laguinho/routes/datasets.py
> +    return result
Tem um status code pra `CREATED` que é o 201

2019-09-06 20:11 UTC, JoseRenan commented on laguinho/routes/datasets.py
> +@datasets.route("/publish", methods=['POST'])
Pra padronizar com o REST, o ideal seria que a rota fosse só `/datasets`

2019-09-06 20:11 UTC, JoseRenan commented on laguinho/routes/datasets.py
> +def get_metadata():
Não seria melhor um nome como `retrieve_datasets` ou `get_datasets` ou `list_datasets`?

2019-09-06 20:11 UTC, JoseRenan commented on laguinho/models/metadata.py
> +    name = fields.Str(required=True, error_messages={"required": {"message": "Name is required."}})
talvez criar uma função `get_error`ou `gen_error` ficasse massa, só pra retornar esse objeto, porque ele repete muitas vezes, alguma coisa como:

```python
def get_required_error(attribute):
    return { "required": { "message": attribute + " is required" } }
```

2019-09-06 20:11 UTC, JoseRenan commented on laguinho/models/metadata.py
> +class MetadataSchema(Schema):
DatasetMetadata talvez fosse mais específico, porque podemos querer adicionar metadados de outras coisas depois 🤔

2019-09-06 21:48 UTC, lucasmedeiros requested changes
Muito obrigado pelo interesse no projeto, ficou ótimo! Tô mandando algumas correçõeszinhas pequenas, algumas @JoseRenan até já tinha comentado. No mais, ficou muito bom mesmo.

2019-09-06 21:48 UTC, lucasmedeiros commented on laguinho/models/metadata.py
> +    format = fields.Str(validate=validate.OneOf(["json", "csv"]), required=True, error_messages={"required": {"message": "Format is required."}})
Acho que seria legal a gente começar desde já a utilizar os padrões do [PEP8](https://www.python.org/dev/peps/pep-0008/) pra documentação e codificação mesmo. Até facilita a vida de quem for começar a contribuir.

2019-09-06 21:48 UTC, lucasmedeiros commented on laguinho/models/metadata.py
> +class MetadataSchema(Schema):
`DatasetMetadataSchema` provavelmente seria o melhor nome, por padrões de *clean code*.

2019-09-06 21:48 UTC, lucasmedeiros commented on laguinho/models/metadata.py
> +    name = fields.Str(required=True, error_messages={"required": {"message": "Name is required."}})
De acordo!

2019-09-06 21:48 UTC, lucasmedeiros commented on laguinho/routes/datasets.py
> +@datasets.route("/publish", methods=['POST'])
Sim, aí seria a rota `/datasets` tanto pra `GET` quanto para `POST`.

2019-09-06 21:48 UTC, lucasmedeiros commented on laguinho/routes/datasets.py
> +    return jsonify(metadata)
Acho que aqui a gente precisaria receber dados do `header`, `body`, ou até dos próprios `params` da URL para pegar um objeto específico do dataset. Creio que não é muito jogo retornar todos de uma vez.

Mas você pode deixar isso para eu corrigir em outra outra PR, já que não é o foco dessa. :smile:

2019-09-06 21:49 UTC, lucasmedeiros commented on laguinho/models/metadata.py
> +    name = fields.Str(required=True, error_messages={"required": {"message": "Name is required."}})
De acordo!

2019-09-06 22:50 UTC, JoseRenan commented on laguinho/routes/datasets.py
> +    return jsonify(metadata)
Não tem issue especificando o GET ainda, daí tá esse retornando tudo msm, acho que tudo bem :thinking:

2019-09-06 22:51 UTC, lucasmedeiros commented on laguinho/routes/datasets.py
> +    return jsonify(metadata)
De boas, eu faço em outra issue :stuck_out_tongue:

2019-09-07 00:42 UTC, JoseRenan requested changes

2019-09-07 00:42 UTC, JoseRenan commented on laguinho/models/metadata.py
> +def get_required_error(attribute):
seria bom colocar isso em outro arquivo dentro do models/, porque outros schemas podem usar

2019-09-07 00:42 UTC, JoseRenan commented on laguinho/models/metadata.py
> +    contributable = fields.Bool()
Poderia inicializar o schema logo aqui depois da classe:
```python
dataset_metadata = DatasetMetadataSchema()
```
pra não precisar ficar instanciando quando for usar, é OK ter o schema como um singleton

2019-09-07 00:42 UTC, JoseRenan commented on laguinho/routes/datasets.py
> +from laguinho.models.metadata import DatasetMetadataSchema
já importar a instancia do schema, invés da classe como sugerido na outra issue

2019-09-07 00:42 UTC, JoseRenan commented on laguinho/routes/datasets.py
> +    return jsonify(datasets_metadata)
não dá pra usar o schema aqui também? pra gente padronizar uma forma só de parse pra JSON?

2019-09-08 02:51 UTC, JoseRenan approved these changes
Topppp meu patrão, mto bom msm!!! Valeu :heart:

2019-09-08 03:00 UTC, lucasmedeiros approved these changes
Show de bola!

2019-09-08 03:00 UTC, merged