Adiciona changelog ao projeto
OpenDevUFCG/laguinho-api pull request #52
Opened 2019-09-10 18:29 UTC by lucasmedeiros

Resolves #36 

Esta PR adiciona um CHANGELOG à branch `development`, como foi sugerido por @thayannevls.

2019-09-10 19:40 UTC, JoseRenan requested changes

2019-09-10 19:40 UTC, JoseRenan commented on CHANGELOG.md
> +- Endpoint `/datasets/<nome>/` para requisições GET, que vai retornar metadados a respeito de um dataset a partir do seu nome.
Esse endpoint ainda não está feito no momento desse PR, tem de ser adicionado no outro PR

2019-09-11 19:47 UTC, thayannevls requested changes

2019-09-11 19:47 UTC, thayannevls commented on CHANGELOG.md
> +---
Tira isso `---`

Só se deixa *1* linha vazia.

2019-09-11 19:55 UTC, thayannevls approved these changes

2019-09-18 04:25 UTC, JoseRenan commented on CHANGELOG.md
> +- Endpoint `/datasets/<nome>/` para requisições GET, que vai retornar metadados a respeito de um dataset a partir do seu nome.
Agora está! KKKKK

2019-09-18 04:25 UTC, JoseRenan approved these changes

2019-09-18 04:25 UTC, merged