Adiciona arquivos guidelines restantes.
OpenDevUFCG/laguinho-api pull request #57
Opened 2019-10-01 17:30 UTC by lucasmedeiros

Fixes #54.

Esta PR adiciona os arquivos guidelines restantes para o projeto: templates de issues e de pull request, conforme requere a issue a qual esta se refere.

2019-10-01 18:12 UTC, thayannevls commented on .github/ISSUE_TEMPLATE/bug_report.md
> +---
Apenas um comentário: Pessoalmente prefiro templates em que as indicações sejam comentário `<!-- -->`, dá uma olhada pra ver oq acha ;)

2019-10-01 22:08 UTC, lucasmedeiros commented
@thayannevls Feito!

2019-10-02 09:12 UTC, paulojbleitao requested changes

2019-10-02 09:12 UTC, paulojbleitao commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Desktop:**
Achei meio esquisito esse nome, talvez algo tipo "configuração do ambiente" ou coisa parecida seja melhor :thinking:

2019-10-02 13:01 UTC, lucasmedeiros commented
@paulojbleitao feito!

2019-10-02 13:24 UTC, thayannevls approved these changes

2019-10-02 17:57 UTC, paulojbleitao approved these changes

2019-10-02 17:57 UTC, merged