Adiciona rota base para retornar todas as disciplinas e suas informações
OpenDevUFCG/laguinho-api pull request #6
Opened 2019-02-17 14:20 UTC by JuanBarros2

Fixes #5

2019-02-22 17:33 UTC, JoseRenan requested changes
Pedi umas alterações simples só pra padronizar com o código que já tem ❤️

2019-02-22 17:33 UTC, JoseRenan commented on docs/SUBJECTS.md
> +### `GET /v1/subjects` - Recuperar informações de disciplinas de computação na UFCG.
Talvez seja interessante informar que são as discplinas da PPC 2017

2019-02-22 17:33 UTC, JoseRenan commented on docs/SUBJECTS.md
> +#### Como contribuir adicionando mais repositórios
```suggestion
#### Como contribuir adicionando outras disciplinas
```

2019-02-22 17:33 UTC, JoseRenan commented on src/v1/subjects/subj-data.js
> +    return await csv().fromStream(request.get(csvFilePath))
A gente tá usando o axios pra fazer request HTTP por ser mais leve que o request no `node_modules` no caso só mudaria pra `axios.get(csvFilePath)` ao invés de `request.get`

2019-02-22 18:38 UTC, JuanBarros2 commented on src/v1/subjects/subj-data.js
> +    return await csv().fromStream(request.get(csvFilePath))
Aaa sim. Pensei em usar o axios mas me pareceu exagero. Já que vcs já estão utilizando posso arrumar pra usar o axios msm

2019-02-25 20:43 UTC, JoseRenan approved these changes
Toppp mermão ❤️ 🚀

2019-02-25 20:44 UTC, merged